<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PromiseA+规范</title>
</head>

<body>
    <script>
        // 先定义三个常量表示状态
        const PENDING = 'pending';
        const FULFILLED = 'fulfilled';
        const REJECTED = 'rejected';
        class MyPromise {
            constructor(executor) {
                this.status = PENDING;
                this.value = null;
                this.reason = null;
                // 存储成功回调函数
                this.onFulfilledCallback = [];
                // 存储失败回调函数
                this.onRejectedCallback = [];
                try {
                    // executor 是一个执行器，进入会立即执行
                    executor(this.resolve, this.reject);
                } catch (error) {
                    this.reject(error);
                }

            }
            resolve = (value) => {
                if (this.status !== PENDING) return;
                // 更改期约状态
                this.status = FULFILLED;
                // 更改成功之后的值
                this.value = value;
                // 判定成功回调是否存在，如果存在就进行调用
                // this.onFulfilledCallback && this.onFulfilledCallback(value);
                while (this.onFulfilledCallback.length) {
                    this.onFulfilledCallback.shift()(value);
                }
            }
            reject = (reason) => {
                if (this.status !== PENDING) return;
                this.status = REJECTED;
                this.reason = reason;
                // 判定失败回调是否存在，如果存在就进行调用
                // this.onRejectedCallback && this.onRejectedCallback(reason);
                while (this.onFulfilledCallback.length) {
                    this.onRejectedCallback.shift()(reason);
                }
            }
            // then的作用是返回
            then(onFulfilled, onRejected) {
                // 如果不传，就使用默认函数
                onFulfilled = typeof onFulfilled === 'function' ? onFulfilled : value => value;
                onRejected = typeof onRejected === 'function' ? onRejected : reason => { throw reason };

                // 为了链式调用这里直接创建一个MyPromise，并在后面return出去
                const promise2 = new MyPromise((resolve, reject) => {
                    // console.log("当前的this", this);
                    // 这里的内容在执行器中，会立即执行
                    if (this.status === FULFILLED) {
                        // 创建一个微任务等待 promise2 完成初始化
                        queueMicrotask(() => {
                            try {
                                // 获取成功回调函数的执行结果
                                const x = onFulfilled(this.value);
                                // 传入 resolvePromise 集中处理
                                resolvePromise(promise2, x, resolve, reject);
                            } catch (error) {
                                reject(error)
                            }
                        })
                    } else if (this.status === REJECTED) {
                        // ==== 新增 ====
                        // 创建一个微任务等待 promise2 完成初始化
                        queueMicrotask(() => {
                            try {
                                // 调用失败回调，并且把原因返回
                                const x = onRejected(this.reason);
                                // 传入 resolvePromise 集中处理
                                resolvePromise(promise2, x, resolve, reject);
                            } catch (error) {
                                reject(error)
                            }
                        })
                    } else if (this.status === PENDING) {   // pending状态主要处理异步的，状态还没有变化
                        // 因为不知道后面状态的变化情况，所以在Pending的状态下，先将成功回调和失败回调都先存储起来
                        // 等待执行成功失败函数的时候再进行传递
                        // this.onFulfilledCallback = onFulfilled;
                        // this.onRejectedCallback = onRejected;
                        // this.onFulfilledCallback.push(onFulfilled);
                        // this.onRejectedCallback.push(onRejected);
                        this.onFulfilledCallback.push(() => {
                            // ==== 新增 ====
                            queueMicrotask(() => {
                                try {
                                    // 获取成功回调函数的执行结果
                                    const x = onFulfilled(this.value);
                                    // 传入 resolvePromise 集中处理
                                    resolvePromise(promise2, x, resolve, reject);
                                } catch (error) {
                                    reject(error)
                                }
                            })
                        });
                        this.onRejectedCallback.push(() => {
                            // ==== 新增 ====
                            queueMicrotask(() => {
                                try {
                                    // 调用失败回调，并且把原因返回
                                    const x = onRejected(this.reason);
                                    // 传入 resolvePromise 集中处理
                                    resolvePromise(promise2, x, resolve, reject);
                                } catch (error) {
                                    reject(error)
                                }
                            })
                        });
                    }
                })
                return promise2;
            }
        };
        // 处理值穿透问题
        function resolvePromise(promise2, x, resolve, reject) {
            // if (promise2 === x) {
            //     return reject(new TypeError('Chaining cycle detected for promise #<Promise>'))
            // }
            // 判断x是不是 MyPromise 实例对象
            if (x instanceof MyPromise) {
                // x是返回的一个新的promise，所以初始状态仍然是pending
                // 执行 x，调用 then 方法，现在的状态的pending了。[目的是将其状态变为 fulfilled 或者 rejected]
                // 值穿透
                x.then(value => { console.log(`执行了resolve${value}`); resolve(value) }, reason => reject(reason))
                // 简化之后
                // x.then(resolve, reject)
            } else {
                // 普通值
                // console.log('普通纸');
                resolve(x)
            }
        }
        // function other() {
        //     return new MyPromise((resolve, reject) => {
        //         console.log('执行了other');
        //         resolve('other')
        //     })
        // }

        // const promise = new MyPromise((resolve, reject) => {
        //     console.log('执行器');
        //     resolve('success~')
        // });
        // promise.then(value => {
        //     console.log(1)
        //     console.log('resolve', value)
        //     return other()
        //     // return 2
        // }).then(value => {
        //     console.log(2)
        //     console.log('resolve', value)
        // })
        // 这个时候将promise定义一个p1，然后返回的时候返回p1这个promise
        const promise = new MyPromise((resolve, reject) => {
            resolve('succ')
        })

        promise.then().then().then(value => { console.log('执行了'); console.log(value) })


    </script>
</body>

</html>